version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies"
      include: "scope"
    target-branch: "main"