name: quickaid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  highlight_text: ^1.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
