name: quickaid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_tts: ^3.8.5
  geolocator: ^11.0.0
  highlight_text: ^1.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
