name: Build APK

on:
  push:
    branches:
      - main  # Set a branch to trigger this workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v1
        # No need to specify a version, it will set up the latest stable version by default

      - name: Install dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Build APK
        run: |
          cd frontend
          flutter build apk --target-platform android-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
